// This file was automatically generated by bifcl from /usr/src/packages/BUILD/src/packet_analysis/protocol/teredo/events.bif (plugin mode).

#if defined(ZEEK_IN_NETVAR) || ! defined(_usr_src_packages_BUILD_build_src_packet_analysis_protocol_teredo_events_bif)
#ifndef ZEEK_IN_NETVAR
#ifndef _usr_src_packages_BUILD_build_src_packet_analysis_protocol_teredo_events_bif
#define _usr_src_packages_BUILD_build_src_packet_analysis_protocol_teredo_events_bif
#include "zeek/zeek-bif.h"
#endif
#endif

extern zeek::EventHandlerPtr teredo_packet; 
namespace zeek { namespace BifEvent {  void enqueue_teredo_packet(zeek::analyzer::Analyzer* analyzer, zeek::Connection* outer, zeek::IntrusivePtr<zeek::Val> inner);  }  }
extern zeek::EventHandlerPtr new_teredo_state; 
namespace zeek { namespace BifEvent {  void enqueue_new_teredo_state(zeek::analyzer::Analyzer* analyzer, zeek::Connection* c);  }  }
extern zeek::EventHandlerPtr teredo_authentication; 
namespace zeek { namespace BifEvent {  void enqueue_teredo_authentication(zeek::analyzer::Analyzer* analyzer, zeek::Connection* outer, zeek::IntrusivePtr<zeek::Val> inner);  }  }
extern zeek::EventHandlerPtr teredo_origin_indication; 
namespace zeek { namespace BifEvent {  void enqueue_teredo_origin_indication(zeek::analyzer::Analyzer* analyzer, zeek::Connection* outer, zeek::IntrusivePtr<zeek::Val> inner);  }  }
extern zeek::EventHandlerPtr teredo_bubble; 
namespace zeek { namespace BifEvent {  void enqueue_teredo_bubble(zeek::analyzer::Analyzer* analyzer, zeek::Connection* outer, zeek::IntrusivePtr<zeek::Val> inner);  }  }

#endif
