// This file was automatically generated by bifcl from /usr/src/packages/BUILD/src/probabilistic/cardinality-counter.bif (alternative mode).

#if defined(ZEEK_IN_NETVAR) || ! defined(_usr_src_packages_BUILD_build_src_probabilistic_cardinality_counter_bif)
#ifndef ZEEK_IN_NETVAR
#ifndef _usr_src_packages_BUILD_build_src_probabilistic_cardinality_counter_bif
#define _usr_src_packages_BUILD_build_src_probabilistic_cardinality_counter_bif
#include "zeek/zeek-bif.h"
#endif
#endif

namespace zeek { namespace BifFunc { extern zeek::ValPtr hll_cardinality_init_bif(zeek::detail::Frame* frame, const zeek::Args*); }  }
namespace zeek { namespace BifFunc { extern zeek::ValPtr hll_cardinality_add_bif(zeek::detail::Frame* frame, const zeek::Args*); }  }
namespace zeek { namespace BifFunc { extern zeek::ValPtr hll_cardinality_merge_into_bif(zeek::detail::Frame* frame, const zeek::Args*); }  }
namespace zeek { namespace BifFunc { extern zeek::ValPtr hll_cardinality_estimate_bif(zeek::detail::Frame* frame, const zeek::Args*); }  }
namespace zeek { namespace BifFunc { extern zeek::ValPtr hll_cardinality_copy_bif(zeek::detail::Frame* frame, const zeek::Args*); }  }

#endif
