// This file was automatically generated by bifcl from /usr/src/packages/BUILD/src/analyzer/protocol/xmpp/events.bif (plugin mode).

#if defined(ZEEK_IN_NETVAR) || ! defined(_usr_src_packages_BUILD_build_src_analyzer_protocol_xmpp_events_bif)
#ifndef ZEEK_IN_NETVAR
#ifndef _usr_src_packages_BUILD_build_src_analyzer_protocol_xmpp_events_bif
#define _usr_src_packages_BUILD_build_src_analyzer_protocol_xmpp_events_bif
#include "zeek/zeek-bif.h"
#endif
#endif

extern zeek::EventHandlerPtr xmpp_starttls; 
namespace zeek { namespace BifEvent {  void enqueue_xmpp_starttls(zeek::analyzer::Analyzer* analyzer, zeek::Connection* c);  }  }

#endif
