// This file was automatically generated by bifcl from /usr/src/packages/BUILD/src/file_analysis/analyzer/entropy/events.bif (plugin mode).

#if defined(ZEEK_IN_NETVAR) || ! defined(_usr_src_packages_BUILD_build_src_file_analysis_analyzer_entropy_events_bif)
#ifndef ZEEK_IN_NETVAR
#ifndef _usr_src_packages_BUILD_build_src_file_analysis_analyzer_entropy_events_bif
#define _usr_src_packages_BUILD_build_src_file_analysis_analyzer_entropy_events_bif
#include "zeek/zeek-bif.h"
#endif
#endif

extern zeek::EventHandlerPtr file_entropy; 
namespace zeek { namespace BifEvent {  void enqueue_file_entropy(zeek::analyzer::Analyzer* analyzer, zeek::IntrusivePtr<zeek::Val> f, zeek::IntrusivePtr<zeek::Val> ent);  }  }

#endif
