// This file was automatically generated by bifcl from /usr/src/packages/BUILD/src/analyzer/protocol/snmp/types.bif (plugin mode).

#if defined(ZEEK_IN_NETVAR) || ! defined(_usr_src_packages_BUILD_build_src_analyzer_protocol_snmp_types_bif)
#ifndef ZEEK_IN_NETVAR
#ifndef _usr_src_packages_BUILD_build_src_analyzer_protocol_snmp_types_bif
#define _usr_src_packages_BUILD_build_src_analyzer_protocol_snmp_types_bif
#include "zeek/zeek-bif.h"
#endif
#endif

namespace zeek { namespace BifType { namespace Record{ namespace SNMP {  extern zeek::IntrusivePtr<zeek::RecordType> Header;  } } }}
namespace zeek { namespace BifType { namespace Record{ namespace SNMP {  extern zeek::IntrusivePtr<zeek::RecordType> HeaderV1;  } } }}
namespace zeek { namespace BifType { namespace Record{ namespace SNMP {  extern zeek::IntrusivePtr<zeek::RecordType> HeaderV2;  } } }}
namespace zeek { namespace BifType { namespace Record{ namespace SNMP {  extern zeek::IntrusivePtr<zeek::RecordType> HeaderV3;  } } }}
namespace zeek { namespace BifType { namespace Record{ namespace SNMP {  extern zeek::IntrusivePtr<zeek::RecordType> PDU;  } } }}
namespace zeek { namespace BifType { namespace Record{ namespace SNMP {  extern zeek::IntrusivePtr<zeek::RecordType> TrapPDU;  } } }}
namespace zeek { namespace BifType { namespace Record{ namespace SNMP {  extern zeek::IntrusivePtr<zeek::RecordType> BulkPDU;  } } }}
namespace zeek { namespace BifType { namespace Record{ namespace SNMP {  extern zeek::IntrusivePtr<zeek::RecordType> ScopedPDU_Context;  } } }}
namespace zeek { namespace BifType { namespace Record{ namespace SNMP {  extern zeek::IntrusivePtr<zeek::RecordType> ObjectValue;  } } }}
namespace zeek { namespace BifType { namespace Record{ namespace SNMP {  extern zeek::IntrusivePtr<zeek::RecordType> Binding;  } } }}
namespace zeek { namespace BifType { namespace Vector{ namespace SNMP {  extern zeek::IntrusivePtr<zeek::VectorType> Bindings;  } } }}

#endif
