// This file was automatically generated by bifcl from /usr/src/packages/BUILD/src/analyzer/protocol/conn-size/events.bif (plugin mode).

#if defined(ZEEK_IN_NETVAR) || ! defined(_usr_src_packages_BUILD_build_src_analyzer_protocol_conn_size_events_bif)
#ifndef ZEEK_IN_NETVAR
#ifndef _usr_src_packages_BUILD_build_src_analyzer_protocol_conn_size_events_bif
#define _usr_src_packages_BUILD_build_src_analyzer_protocol_conn_size_events_bif
#include "zeek/zeek-bif.h"
#endif
#endif

extern zeek::EventHandlerPtr conn_bytes_threshold_crossed; 
namespace zeek { namespace BifEvent {  void enqueue_conn_bytes_threshold_crossed(zeek::analyzer::Analyzer* analyzer, zeek::Connection* c, zeek_uint_t threshold, int is_orig);  }  }
extern zeek::EventHandlerPtr conn_packets_threshold_crossed; 
namespace zeek { namespace BifEvent {  void enqueue_conn_packets_threshold_crossed(zeek::analyzer::Analyzer* analyzer, zeek::Connection* c, zeek_uint_t threshold, int is_orig);  }  }
extern zeek::EventHandlerPtr conn_duration_threshold_crossed; 
namespace zeek { namespace BifEvent {  void enqueue_conn_duration_threshold_crossed(zeek::analyzer::Analyzer* analyzer, zeek::Connection* c, double threshold, int is_orig);  }  }

#endif
