// This file was automatically generated by bifcl from /usr/src/packages/BUILD/src/analyzer/protocol/conn-size/functions.bif (plugin mode).

#if defined(ZEEK_IN_NETVAR) || ! defined(_usr_src_packages_BUILD_build_src_analyzer_protocol_conn_size_functions_bif)
#ifndef ZEEK_IN_NETVAR
#ifndef _usr_src_packages_BUILD_build_src_analyzer_protocol_conn_size_functions_bif
#define _usr_src_packages_BUILD_build_src_analyzer_protocol_conn_size_functions_bif
#include "zeek/zeek-bif.h"
#endif
#endif

namespace zeek { namespace BifFunc { extern zeek::ValPtr set_current_conn_bytes_threshold_bif(zeek::detail::Frame* frame, const zeek::Args*); }  }
namespace zeek { namespace BifFunc { extern zeek::ValPtr set_current_conn_packets_threshold_bif(zeek::detail::Frame* frame, const zeek::Args*); }  }
namespace zeek { namespace BifFunc { extern zeek::ValPtr set_current_conn_duration_threshold_bif(zeek::detail::Frame* frame, const zeek::Args*); }  }
namespace zeek { namespace BifFunc { extern zeek::ValPtr get_current_conn_bytes_threshold_bif(zeek::detail::Frame* frame, const zeek::Args*); }  }
namespace zeek { namespace BifFunc { extern zeek::ValPtr get_current_conn_packets_threshold_bif(zeek::detail::Frame* frame, const zeek::Args*); }  }
namespace zeek { namespace BifFunc { extern zeek::ValPtr get_current_conn_duration_threshold_bif(zeek::detail::Frame* frame, const zeek::Args*); }  }

#endif
