// This file was automatically generated by bifcl from /usr/src/packages/BUILD/src/analyzer/protocol/websocket/consts.bif (plugin mode).

#if defined(ZEEK_IN_NETVAR) || ! defined(_usr_src_packages_BUILD_build_src_analyzer_protocol_websocket_consts_bif)
#ifndef ZEEK_IN_NETVAR
#ifndef _usr_src_packages_BUILD_build_src_analyzer_protocol_websocket_consts_bif
#define _usr_src_packages_BUILD_build_src_analyzer_protocol_websocket_consts_bif
#include "zeek/zeek-bif.h"
#endif
#endif

namespace zeek { namespace BifConst { namespace WebSocket {  extern zeek_uint_t payload_chunk_size;  }  } }

#endif
