// This file was automatically generated by bifcl from /usr/src/packages/BUILD/src/analyzer/protocol/websocket/functions.bif (plugin mode).

#if defined(ZEEK_IN_NETVAR) || ! defined(_usr_src_packages_BUILD_build_src_analyzer_protocol_websocket_functions_bif)
#ifndef ZEEK_IN_NETVAR
#ifndef _usr_src_packages_BUILD_build_src_analyzer_protocol_websocket_functions_bif
#define _usr_src_packages_BUILD_build_src_analyzer_protocol_websocket_functions_bif
#include "zeek/zeek-bif.h"
#endif
#endif

namespace zeek { namespace BifFunc { namespace WebSocket { extern zeek::ValPtr __configure_analyzer_bif(zeek::detail::Frame* frame, const zeek::Args*); }  } }

#endif
