// This file was automatically generated by bifcl from /usr/src/packages/BUILD/src/analyzer/protocol/smb/events.bif (plugin mode).

#if defined(ZEEK_IN_NETVAR) || ! defined(_usr_src_packages_BUILD_build_src_analyzer_protocol_smb_events_bif)
#ifndef ZEEK_IN_NETVAR
#ifndef _usr_src_packages_BUILD_build_src_analyzer_protocol_smb_events_bif
#define _usr_src_packages_BUILD_build_src_analyzer_protocol_smb_events_bif
#include "zeek/zeek-bif.h"
#endif
#endif

extern zeek::EventHandlerPtr smb_pipe_connect_heuristic; 
namespace zeek { namespace BifEvent {  void enqueue_smb_pipe_connect_heuristic(zeek::analyzer::Analyzer* analyzer, zeek::Connection* c);  }  }
extern zeek::EventHandlerPtr smb_discarded_dce_rpc_analyzers; 
namespace zeek { namespace BifEvent {  void enqueue_smb_discarded_dce_rpc_analyzers(zeek::analyzer::Analyzer* analyzer, zeek::Connection* c);  }  }

#endif
