// This file was automatically generated by bifcl from /usr/src/packages/BUILD/src/analyzer/protocol/smb/smb1_com_transaction.bif (plugin mode).

#if defined(ZEEK_IN_NETVAR) || ! defined(_usr_src_packages_BUILD_build_src_analyzer_protocol_smb_smb1_com_transaction_bif)
#ifndef ZEEK_IN_NETVAR
#ifndef _usr_src_packages_BUILD_build_src_analyzer_protocol_smb_smb1_com_transaction_bif
#define _usr_src_packages_BUILD_build_src_analyzer_protocol_smb_smb1_com_transaction_bif
#include "zeek/zeek-bif.h"
#endif
#endif

extern zeek::EventHandlerPtr smb1_transaction_request; 
namespace zeek { namespace BifEvent {  void enqueue_smb1_transaction_request(zeek::analyzer::Analyzer* analyzer, zeek::Connection* c, zeek::IntrusivePtr<zeek::Val> hdr, zeek::IntrusivePtr<zeek::StringVal> name, zeek_uint_t sub_cmd, zeek::IntrusivePtr<zeek::StringVal> parameters, zeek::IntrusivePtr<zeek::StringVal> data);  }  }
extern zeek::EventHandlerPtr smb1_transaction_response; 
namespace zeek { namespace BifEvent {  void enqueue_smb1_transaction_response(zeek::analyzer::Analyzer* analyzer, zeek::Connection* c, zeek::IntrusivePtr<zeek::Val> hdr, zeek::IntrusivePtr<zeek::StringVal> parameters, zeek::IntrusivePtr<zeek::StringVal> data);  }  }

#endif
