// This file was automatically generated by bifcl from /usr/src/packages/BUILD/src/analyzer/protocol/smb/smb1_events.bif (plugin mode).

#if defined(ZEEK_IN_NETVAR) || ! defined(_usr_src_packages_BUILD_build_src_analyzer_protocol_smb_smb1_events_bif)
#ifndef ZEEK_IN_NETVAR
#ifndef _usr_src_packages_BUILD_build_src_analyzer_protocol_smb_smb1_events_bif
#define _usr_src_packages_BUILD_build_src_analyzer_protocol_smb_smb1_events_bif
#include "zeek/zeek-bif.h"
#endif
#endif

extern zeek::EventHandlerPtr smb1_message; 
namespace zeek { namespace BifEvent {  void enqueue_smb1_message(zeek::analyzer::Analyzer* analyzer, zeek::Connection* c, zeek::IntrusivePtr<zeek::Val> hdr, int is_orig);  }  }
extern zeek::EventHandlerPtr smb1_empty_response; 
namespace zeek { namespace BifEvent {  void enqueue_smb1_empty_response(zeek::analyzer::Analyzer* analyzer, zeek::Connection* c, zeek::IntrusivePtr<zeek::Val> hdr);  }  }
extern zeek::EventHandlerPtr smb1_error; 
namespace zeek { namespace BifEvent {  void enqueue_smb1_error(zeek::analyzer::Analyzer* analyzer, zeek::Connection* c, zeek::IntrusivePtr<zeek::Val> hdr, int is_orig);  }  }

#endif
