// This file was automatically generated by bifcl from /usr/src/packages/BUILD/src/analyzer/protocol/smb/smb1_com_tree_connect_andx.bif (plugin mode).

#if defined(ZEEK_IN_NETVAR) || ! defined(_usr_src_packages_BUILD_build_src_analyzer_protocol_smb_smb1_com_tree_connect_andx_bif)
#ifndef ZEEK_IN_NETVAR
#ifndef _usr_src_packages_BUILD_build_src_analyzer_protocol_smb_smb1_com_tree_connect_andx_bif
#define _usr_src_packages_BUILD_build_src_analyzer_protocol_smb_smb1_com_tree_connect_andx_bif
#include "zeek/zeek-bif.h"
#endif
#endif

extern zeek::EventHandlerPtr smb1_tree_connect_andx_request; 
namespace zeek { namespace BifEvent {  void enqueue_smb1_tree_connect_andx_request(zeek::analyzer::Analyzer* analyzer, zeek::Connection* c, zeek::IntrusivePtr<zeek::Val> hdr, zeek::IntrusivePtr<zeek::StringVal> path, zeek::IntrusivePtr<zeek::StringVal> service);  }  }
extern zeek::EventHandlerPtr smb1_tree_connect_andx_response; 
namespace zeek { namespace BifEvent {  void enqueue_smb1_tree_connect_andx_response(zeek::analyzer::Analyzer* analyzer, zeek::Connection* c, zeek::IntrusivePtr<zeek::Val> hdr, zeek::IntrusivePtr<zeek::StringVal> service, zeek::IntrusivePtr<zeek::StringVal> native_file_system);  }  }

#endif
