// This file was automatically generated by bifcl from /usr/src/packages/BUILD/src/analyzer/protocol/smb/smb1_com_tree_disconnect.bif (plugin mode).

#if defined(ZEEK_IN_NETVAR) || ! defined(_usr_src_packages_BUILD_build_src_analyzer_protocol_smb_smb1_com_tree_disconnect_bif)
#ifndef ZEEK_IN_NETVAR
#ifndef _usr_src_packages_BUILD_build_src_analyzer_protocol_smb_smb1_com_tree_disconnect_bif
#define _usr_src_packages_BUILD_build_src_analyzer_protocol_smb_smb1_com_tree_disconnect_bif
#include "zeek/zeek-bif.h"
#endif
#endif

extern zeek::EventHandlerPtr smb1_tree_disconnect; 
namespace zeek { namespace BifEvent {  void enqueue_smb1_tree_disconnect(zeek::analyzer::Analyzer* analyzer, zeek::Connection* c, zeek::IntrusivePtr<zeek::Val> hdr, int is_orig);  }  }

#endif
