// This file was automatically generated by bifcl from /usr/src/packages/BUILD/src/analyzer/protocol/smb/smb1_com_negotiate.bif (plugin mode).

#if defined(ZEEK_IN_NETVAR) || ! defined(_usr_src_packages_BUILD_build_src_analyzer_protocol_smb_smb1_com_negotiate_bif)
#ifndef ZEEK_IN_NETVAR
#ifndef _usr_src_packages_BUILD_build_src_analyzer_protocol_smb_smb1_com_negotiate_bif
#define _usr_src_packages_BUILD_build_src_analyzer_protocol_smb_smb1_com_negotiate_bif
#include "zeek/zeek-bif.h"
#endif
#endif

extern zeek::EventHandlerPtr smb1_negotiate_request; 
namespace zeek { namespace BifEvent {  void enqueue_smb1_negotiate_request(zeek::analyzer::Analyzer* analyzer, zeek::Connection* c, zeek::IntrusivePtr<zeek::Val> hdr, zeek::IntrusivePtr<zeek::Val> dialects);  }  }
extern zeek::EventHandlerPtr smb1_negotiate_response; 
namespace zeek { namespace BifEvent {  void enqueue_smb1_negotiate_response(zeek::analyzer::Analyzer* analyzer, zeek::Connection* c, zeek::IntrusivePtr<zeek::Val> hdr, zeek::IntrusivePtr<zeek::Val> response);  }  }
namespace zeek { namespace BifType { namespace Record{ namespace SMB1 {  extern zeek::IntrusivePtr<zeek::RecordType> NegotiateResponse;  } } }}
namespace zeek { namespace BifType { namespace Record{ namespace SMB1 {  extern zeek::IntrusivePtr<zeek::RecordType> NegotiateResponseCore;  } } }}
namespace zeek { namespace BifType { namespace Record{ namespace SMB1 {  extern zeek::IntrusivePtr<zeek::RecordType> NegotiateResponseLANMAN;  } } }}
namespace zeek { namespace BifType { namespace Record{ namespace SMB1 {  extern zeek::IntrusivePtr<zeek::RecordType> NegotiateResponseNTLM;  } } }}
namespace zeek { namespace BifType { namespace Record{ namespace SMB1 {  extern zeek::IntrusivePtr<zeek::RecordType> NegotiateResponseSecurity;  } } }}
namespace zeek { namespace BifType { namespace Record{ namespace SMB1 {  extern zeek::IntrusivePtr<zeek::RecordType> NegotiateRawMode;  } } }}
namespace zeek { namespace BifType { namespace Record{ namespace SMB1 {  extern zeek::IntrusivePtr<zeek::RecordType> NegotiateCapabilities;  } } }}

#endif
