// This file was automatically generated by bifcl from /usr/src/packages/BUILD/src/analyzer/protocol/smb/smb1_com_echo.bif (plugin mode).

#if defined(ZEEK_IN_NETVAR) || ! defined(_usr_src_packages_BUILD_build_src_analyzer_protocol_smb_smb1_com_echo_bif)
#ifndef ZEEK_IN_NETVAR
#ifndef _usr_src_packages_BUILD_build_src_analyzer_protocol_smb_smb1_com_echo_bif
#define _usr_src_packages_BUILD_build_src_analyzer_protocol_smb_smb1_com_echo_bif
#include "zeek/zeek-bif.h"
#endif
#endif

extern zeek::EventHandlerPtr smb1_echo_request; 
namespace zeek { namespace BifEvent {  void enqueue_smb1_echo_request(zeek::analyzer::Analyzer* analyzer, zeek::Connection* c, zeek_uint_t echo_count, zeek::IntrusivePtr<zeek::StringVal> data);  }  }
extern zeek::EventHandlerPtr smb1_echo_response; 
namespace zeek { namespace BifEvent {  void enqueue_smb1_echo_response(zeek::analyzer::Analyzer* analyzer, zeek::Connection* c, zeek_uint_t seq_num, zeek::IntrusivePtr<zeek::StringVal> data);  }  }

#endif
