// This file was automatically generated by bifcl from /usr/src/packages/BUILD/src/analyzer/protocol/smb/smb1_com_session_setup_andx.bif (plugin mode).

#if defined(ZEEK_IN_NETVAR) || ! defined(_usr_src_packages_BUILD_build_src_analyzer_protocol_smb_smb1_com_session_setup_andx_bif)
#ifndef ZEEK_IN_NETVAR
#ifndef _usr_src_packages_BUILD_build_src_analyzer_protocol_smb_smb1_com_session_setup_andx_bif
#define _usr_src_packages_BUILD_build_src_analyzer_protocol_smb_smb1_com_session_setup_andx_bif
#include "zeek/zeek-bif.h"
#endif
#endif

extern zeek::EventHandlerPtr smb1_session_setup_andx_request; 
namespace zeek { namespace BifEvent {  void enqueue_smb1_session_setup_andx_request(zeek::analyzer::Analyzer* analyzer, zeek::Connection* c, zeek::IntrusivePtr<zeek::Val> hdr, zeek::IntrusivePtr<zeek::Val> request);  }  }
extern zeek::EventHandlerPtr smb1_session_setup_andx_response; 
namespace zeek { namespace BifEvent {  void enqueue_smb1_session_setup_andx_response(zeek::analyzer::Analyzer* analyzer, zeek::Connection* c, zeek::IntrusivePtr<zeek::Val> hdr, zeek::IntrusivePtr<zeek::Val> response);  }  }
namespace zeek { namespace BifType { namespace Record{ namespace SMB1 {  extern zeek::IntrusivePtr<zeek::RecordType> SessionSetupAndXRequest;  } } }}
namespace zeek { namespace BifType { namespace Record{ namespace SMB1 {  extern zeek::IntrusivePtr<zeek::RecordType> SessionSetupAndXResponse;  } } }}
namespace zeek { namespace BifType { namespace Record{ namespace SMB1 {  extern zeek::IntrusivePtr<zeek::RecordType> SessionSetupAndXCapabilities;  } } }}

#endif
