// This file was automatically generated by bifcl from /usr/src/packages/BUILD/src/analyzer/protocol/smb/smb1_com_check_directory.bif (plugin mode).

#if defined(ZEEK_IN_NETVAR) || ! defined(_usr_src_packages_BUILD_build_src_analyzer_protocol_smb_smb1_com_check_directory_bif)
#ifndef ZEEK_IN_NETVAR
#ifndef _usr_src_packages_BUILD_build_src_analyzer_protocol_smb_smb1_com_check_directory_bif
#define _usr_src_packages_BUILD_build_src_analyzer_protocol_smb_smb1_com_check_directory_bif
#include "zeek/zeek-bif.h"
#endif
#endif

extern zeek::EventHandlerPtr smb1_check_directory_request; 
namespace zeek { namespace BifEvent {  void enqueue_smb1_check_directory_request(zeek::analyzer::Analyzer* analyzer, zeek::Connection* c, zeek::IntrusivePtr<zeek::Val> hdr, zeek::IntrusivePtr<zeek::StringVal> directory_name);  }  }
extern zeek::EventHandlerPtr smb1_check_directory_response; 
namespace zeek { namespace BifEvent {  void enqueue_smb1_check_directory_response(zeek::analyzer::Analyzer* analyzer, zeek::Connection* c, zeek::IntrusivePtr<zeek::Val> hdr);  }  }

#endif
