// This file was automatically generated by bifcl from /usr/src/packages/BUILD/src/analyzer/protocol/smb/smb1_com_write_andx.bif (plugin mode).

#if defined(ZEEK_IN_NETVAR) || ! defined(_usr_src_packages_BUILD_build_src_analyzer_protocol_smb_smb1_com_write_andx_bif)
#ifndef ZEEK_IN_NETVAR
#ifndef _usr_src_packages_BUILD_build_src_analyzer_protocol_smb_smb1_com_write_andx_bif
#define _usr_src_packages_BUILD_build_src_analyzer_protocol_smb_smb1_com_write_andx_bif
#include "zeek/zeek-bif.h"
#endif
#endif

extern zeek::EventHandlerPtr smb1_write_andx_request; 
namespace zeek { namespace BifEvent {  void enqueue_smb1_write_andx_request(zeek::analyzer::Analyzer* analyzer, zeek::Connection* c, zeek::IntrusivePtr<zeek::Val> hdr, zeek_uint_t file_id, zeek_uint_t offset, zeek_uint_t data_len);  }  }
extern zeek::EventHandlerPtr smb1_write_andx_response; 
namespace zeek { namespace BifEvent {  void enqueue_smb1_write_andx_response(zeek::analyzer::Analyzer* analyzer, zeek::Connection* c, zeek::IntrusivePtr<zeek::Val> hdr, zeek_uint_t written_bytes);  }  }

#endif
