// This file was automatically generated by bifcl from /usr/src/packages/BUILD/src/analyzer/protocol/smb/smb2_com_session_setup.bif (plugin mode).

#if defined(ZEEK_IN_NETVAR) || ! defined(_usr_src_packages_BUILD_build_src_analyzer_protocol_smb_smb2_com_session_setup_bif)
#ifndef ZEEK_IN_NETVAR
#ifndef _usr_src_packages_BUILD_build_src_analyzer_protocol_smb_smb2_com_session_setup_bif
#define _usr_src_packages_BUILD_build_src_analyzer_protocol_smb_smb2_com_session_setup_bif
#include "zeek/zeek-bif.h"
#endif
#endif

extern zeek::EventHandlerPtr smb2_session_setup_request; 
namespace zeek { namespace BifEvent {  void enqueue_smb2_session_setup_request(zeek::analyzer::Analyzer* analyzer, zeek::Connection* c, zeek::IntrusivePtr<zeek::Val> hdr, zeek::IntrusivePtr<zeek::Val> request);  }  }
extern zeek::EventHandlerPtr smb2_session_setup_response; 
namespace zeek { namespace BifEvent {  void enqueue_smb2_session_setup_response(zeek::analyzer::Analyzer* analyzer, zeek::Connection* c, zeek::IntrusivePtr<zeek::Val> hdr, zeek::IntrusivePtr<zeek::Val> response);  }  }
namespace zeek { namespace BifType { namespace Record{ namespace SMB2 {  extern zeek::IntrusivePtr<zeek::RecordType> SessionSetupRequest;  } } }}
namespace zeek { namespace BifType { namespace Record{ namespace SMB2 {  extern zeek::IntrusivePtr<zeek::RecordType> SessionSetupResponse;  } } }}
namespace zeek { namespace BifType { namespace Record{ namespace SMB2 {  extern zeek::IntrusivePtr<zeek::RecordType> SessionSetupFlags;  } } }}

#endif
