// This file was automatically generated by bifcl from /usr/src/packages/BUILD/src/analyzer/protocol/smb/smb2_events.bif (plugin mode).

#if defined(ZEEK_IN_NETVAR) || ! defined(_usr_src_packages_BUILD_build_src_analyzer_protocol_smb_smb2_events_bif)
#ifndef ZEEK_IN_NETVAR
#ifndef _usr_src_packages_BUILD_build_src_analyzer_protocol_smb_smb2_events_bif
#define _usr_src_packages_BUILD_build_src_analyzer_protocol_smb_smb2_events_bif
#include "zeek/zeek-bif.h"
#endif
#endif

extern zeek::EventHandlerPtr smb2_message; 
namespace zeek { namespace BifEvent {  void enqueue_smb2_message(zeek::analyzer::Analyzer* analyzer, zeek::Connection* c, zeek::IntrusivePtr<zeek::Val> hdr, int is_orig);  }  }
extern zeek::EventHandlerPtr smb2_discarded_messages_state; 
namespace zeek { namespace BifEvent {  void enqueue_smb2_discarded_messages_state(zeek::analyzer::Analyzer* analyzer, zeek::Connection* c, zeek::IntrusivePtr<zeek::StringVal> state);  }  }

#endif
