// This file was automatically generated by bifcl from /usr/src/packages/BUILD/src/analyzer/protocol/smb/smb2_com_transform_header.bif (plugin mode).

#if defined(ZEEK_IN_NETVAR) || ! defined(_usr_src_packages_BUILD_build_src_analyzer_protocol_smb_smb2_com_transform_header_bif)
#ifndef ZEEK_IN_NETVAR
#ifndef _usr_src_packages_BUILD_build_src_analyzer_protocol_smb_smb2_com_transform_header_bif
#define _usr_src_packages_BUILD_build_src_analyzer_protocol_smb_smb2_com_transform_header_bif
#include "zeek/zeek-bif.h"
#endif
#endif

extern zeek::EventHandlerPtr smb2_transform_header; 
namespace zeek { namespace BifEvent {  void enqueue_smb2_transform_header(zeek::analyzer::Analyzer* analyzer, zeek::Connection* c, zeek::IntrusivePtr<zeek::Val> hdr);  }  }
namespace zeek { namespace BifType { namespace Record{ namespace SMB2 {  extern zeek::IntrusivePtr<zeek::RecordType> Transform_header;  } } }}

#endif
