// This file was automatically generated by bifcl from /usr/src/packages/BUILD/src/analyzer/protocol/smb/smb2_com_read.bif (plugin mode).

#if defined(ZEEK_IN_NETVAR) || ! defined(_usr_src_packages_BUILD_build_src_analyzer_protocol_smb_smb2_com_read_bif)
#ifndef ZEEK_IN_NETVAR
#ifndef _usr_src_packages_BUILD_build_src_analyzer_protocol_smb_smb2_com_read_bif
#define _usr_src_packages_BUILD_build_src_analyzer_protocol_smb_smb2_com_read_bif
#include "zeek/zeek-bif.h"
#endif
#endif

extern zeek::EventHandlerPtr smb2_read_request; 
namespace zeek { namespace BifEvent {  void enqueue_smb2_read_request(zeek::analyzer::Analyzer* analyzer, zeek::Connection* c, zeek::IntrusivePtr<zeek::Val> hdr, zeek::IntrusivePtr<zeek::Val> file_id, zeek_uint_t offset, zeek_uint_t length);  }  }

#endif
