// This file was automatically generated by bifcl from /usr/src/packages/BUILD/src/analyzer/protocol/smb/types.bif (plugin mode).

#if defined(ZEEK_IN_NETVAR) || ! defined(_usr_src_packages_BUILD_build_src_analyzer_protocol_smb_types_bif)
#ifndef ZEEK_IN_NETVAR
#ifndef _usr_src_packages_BUILD_build_src_analyzer_protocol_smb_types_bif
#define _usr_src_packages_BUILD_build_src_analyzer_protocol_smb_types_bif
#include "zeek/zeek-bif.h"
#endif
#endif

namespace zeek { namespace BifType { namespace Record{ namespace SMB {  extern zeek::IntrusivePtr<zeek::RecordType> MACTimes;  } } }}
namespace zeek { namespace BifType { namespace Record{ namespace SMB1 {  extern zeek::IntrusivePtr<zeek::RecordType> Header;  } } }}
namespace zeek { namespace BifType { namespace Record{ namespace SMB2 {  extern zeek::IntrusivePtr<zeek::RecordType> Header;  } } }}
namespace zeek { namespace BifType { namespace Record{ namespace SMB2 {  extern zeek::IntrusivePtr<zeek::RecordType> GUID;  } } }}
namespace zeek { namespace BifType { namespace Record{ namespace SMB2 {  extern zeek::IntrusivePtr<zeek::RecordType> FileAttrs;  } } }}
namespace zeek { namespace BifType { namespace Record{ namespace SMB2 {  extern zeek::IntrusivePtr<zeek::RecordType> Fscontrol;  } } }}
namespace zeek { namespace BifType { namespace Record{ namespace SMB2 {  extern zeek::IntrusivePtr<zeek::RecordType> FileEA;  } } }}
namespace zeek { namespace BifType { namespace Vector{ namespace SMB2 {  extern zeek::IntrusivePtr<zeek::VectorType> FileEAs;  } } }}
namespace zeek { namespace BifType { namespace Record{ namespace SMB2 {  extern zeek::IntrusivePtr<zeek::RecordType> PreAuthIntegrityCapabilities;  } } }}
namespace zeek { namespace BifType { namespace Record{ namespace SMB2 {  extern zeek::IntrusivePtr<zeek::RecordType> EncryptionCapabilities;  } } }}
namespace zeek { namespace BifType { namespace Record{ namespace SMB2 {  extern zeek::IntrusivePtr<zeek::RecordType> CompressionCapabilities;  } } }}
namespace zeek { namespace BifType { namespace Record{ namespace SMB2 {  extern zeek::IntrusivePtr<zeek::RecordType> NegotiateContextValue;  } } }}
namespace zeek { namespace BifType { namespace Vector{ namespace SMB2 {  extern zeek::IntrusivePtr<zeek::VectorType> NegotiateContextValues;  } } }}

#endif
