// This file was automatically generated by bifcl from /usr/src/packages/BUILD/src/analyzer/protocol/rdp/types.bif (plugin mode).

#if defined(ZEEK_IN_NETVAR) || ! defined(_usr_src_packages_BUILD_build_src_analyzer_protocol_rdp_types_bif)
#ifndef ZEEK_IN_NETVAR
#ifndef _usr_src_packages_BUILD_build_src_analyzer_protocol_rdp_types_bif
#define _usr_src_packages_BUILD_build_src_analyzer_protocol_rdp_types_bif
#include "zeek/zeek-bif.h"
#endif
#endif

namespace zeek { namespace BifType { namespace Record{ namespace RDP {  extern zeek::IntrusivePtr<zeek::RecordType> EarlyCapabilityFlags;  } } }}
namespace zeek { namespace BifType { namespace Record{ namespace RDP {  extern zeek::IntrusivePtr<zeek::RecordType> ClientCoreData;  } } }}
namespace zeek { namespace BifType { namespace Record{ namespace RDP {  extern zeek::IntrusivePtr<zeek::RecordType> ClientSecurityData;  } } }}
namespace zeek { namespace BifType { namespace Record{ namespace RDP {  extern zeek::IntrusivePtr<zeek::RecordType> ClientClusterData;  } } }}
namespace zeek { namespace BifType { namespace Vector{ namespace RDP {  extern zeek::IntrusivePtr<zeek::VectorType> ClientChannelList;  } } }}
namespace zeek { namespace BifType { namespace Record{ namespace RDP {  extern zeek::IntrusivePtr<zeek::RecordType> ClientChannelDef;  } } }}

#endif
