// This file was automatically generated by bifcl from /usr/src/packages/BUILD/src/file_analysis/file_analysis.bif (alternative mode).

#if defined(ZEEK_IN_NETVAR) || ! defined(_usr_src_packages_BUILD_build_src_file_analysis_file_analysis_bif)
#ifndef ZEEK_IN_NETVAR
#ifndef _usr_src_packages_BUILD_build_src_file_analysis_file_analysis_bif
#define _usr_src_packages_BUILD_build_src_file_analysis_file_analysis_bif
#include "zeek/zeek-bif.h"
#endif
#endif

namespace zeek { namespace BifType { namespace Record{ namespace Files {  extern zeek::IntrusivePtr<zeek::RecordType> AnalyzerArgs;  } } }}
namespace zeek { namespace BifFunc { namespace Files { extern zeek::ValPtr __set_timeout_interval_bif(zeek::detail::Frame* frame, const zeek::Args*); }  } }
namespace zeek { namespace BifFunc { namespace Files { extern zeek::ValPtr __enable_reassembly_bif(zeek::detail::Frame* frame, const zeek::Args*); }  } }
namespace zeek { namespace BifFunc { namespace Files { extern zeek::ValPtr __disable_reassembly_bif(zeek::detail::Frame* frame, const zeek::Args*); }  } }
namespace zeek { namespace BifFunc { namespace Files { extern zeek::ValPtr __set_reassembly_buffer_bif(zeek::detail::Frame* frame, const zeek::Args*); }  } }
namespace zeek { namespace BifFunc { namespace Files { extern zeek::ValPtr __enable_analyzer_bif(zeek::detail::Frame* frame, const zeek::Args*); }  } }
namespace zeek { namespace BifFunc { namespace Files { extern zeek::ValPtr __disable_analyzer_bif(zeek::detail::Frame* frame, const zeek::Args*); }  } }
namespace zeek { namespace BifFunc { namespace Files { extern zeek::ValPtr __analyzer_enabled_bif(zeek::detail::Frame* frame, const zeek::Args*); }  } }
namespace zeek { namespace BifFunc { namespace Files { extern zeek::ValPtr __add_analyzer_bif(zeek::detail::Frame* frame, const zeek::Args*); }  } }
namespace zeek { namespace BifFunc { namespace Files { extern zeek::ValPtr __remove_analyzer_bif(zeek::detail::Frame* frame, const zeek::Args*); }  } }
namespace zeek { namespace BifFunc { namespace Files { extern zeek::ValPtr __stop_bif(zeek::detail::Frame* frame, const zeek::Args*); }  } }
namespace zeek { namespace BifFunc { namespace Files { extern zeek::ValPtr __analyzer_name_bif(zeek::detail::Frame* frame, const zeek::Args*); }  } }
namespace zeek { namespace BifFunc { namespace Files { extern zeek::ValPtr __file_exists_bif(zeek::detail::Frame* frame, const zeek::Args*); }  } }
namespace zeek { namespace BifFunc { namespace Files { extern zeek::ValPtr __lookup_file_bif(zeek::detail::Frame* frame, const zeek::Args*); }  } }
namespace zeek { namespace BifFunc { extern zeek::ValPtr set_file_handle_bif(zeek::detail::Frame* frame, const zeek::Args*); }  }

#endif
