// This file was automatically generated by bifcl from /usr/src/packages/BUILD/src/analyzer/protocol/ncp/events.bif (plugin mode).

#if defined(ZEEK_IN_NETVAR) || ! defined(_usr_src_packages_BUILD_build_src_analyzer_protocol_ncp_events_bif)
#ifndef ZEEK_IN_NETVAR
#ifndef _usr_src_packages_BUILD_build_src_analyzer_protocol_ncp_events_bif
#define _usr_src_packages_BUILD_build_src_analyzer_protocol_ncp_events_bif
#include "zeek/zeek-bif.h"
#endif
#endif

extern zeek::EventHandlerPtr ncp_request; 
namespace zeek { namespace BifEvent {  void enqueue_ncp_request(zeek::analyzer::Analyzer* analyzer, zeek::Connection* c, zeek_uint_t frame_type, zeek_uint_t length, zeek_uint_t func);  }  }
extern zeek::EventHandlerPtr ncp_reply; 
namespace zeek { namespace BifEvent {  void enqueue_ncp_reply(zeek::analyzer::Analyzer* analyzer, zeek::Connection* c, zeek_uint_t frame_type, zeek_uint_t length, zeek_uint_t req_frame, zeek_uint_t req_func, zeek_uint_t completion_code);  }  }

#endif
