// This file was automatically generated by bifcl from /usr/src/packages/BUILD/src/analyzer/protocol/ftp/events.bif (plugin mode).

#if defined(ZEEK_IN_NETVAR) || ! defined(_usr_src_packages_BUILD_build_src_analyzer_protocol_ftp_events_bif)
#ifndef ZEEK_IN_NETVAR
#ifndef _usr_src_packages_BUILD_build_src_analyzer_protocol_ftp_events_bif
#define _usr_src_packages_BUILD_build_src_analyzer_protocol_ftp_events_bif
#include "zeek/zeek-bif.h"
#endif
#endif

extern zeek::EventHandlerPtr ftp_request; 
namespace zeek { namespace BifEvent {  void enqueue_ftp_request(zeek::analyzer::Analyzer* analyzer, zeek::Connection* c, zeek::IntrusivePtr<zeek::StringVal> command, zeek::IntrusivePtr<zeek::StringVal> arg);  }  }
extern zeek::EventHandlerPtr ftp_reply; 
namespace zeek { namespace BifEvent {  void enqueue_ftp_reply(zeek::analyzer::Analyzer* analyzer, zeek::Connection* c, zeek_uint_t code, zeek::IntrusivePtr<zeek::StringVal> msg, int cont_resp);  }  }

#endif
