// This file was automatically generated by bifcl from /usr/src/packages/BUILD/src/analyzer/protocol/ftp/functions.bif (plugin mode).

#if defined(ZEEK_IN_NETVAR) || ! defined(_usr_src_packages_BUILD_build_src_analyzer_protocol_ftp_functions_bif)
#ifndef ZEEK_IN_NETVAR
#ifndef _usr_src_packages_BUILD_build_src_analyzer_protocol_ftp_functions_bif
#define _usr_src_packages_BUILD_build_src_analyzer_protocol_ftp_functions_bif
#include "zeek/zeek-bif.h"
#endif
#endif

namespace zeek { namespace BifType { namespace Record{  extern zeek::IntrusivePtr<zeek::RecordType> ftp_port;  } }}
namespace zeek { namespace BifFunc { extern zeek::ValPtr parse_ftp_port_bif(zeek::detail::Frame* frame, const zeek::Args*); }  }
namespace zeek { namespace BifFunc { extern zeek::ValPtr parse_eftp_port_bif(zeek::detail::Frame* frame, const zeek::Args*); }  }
namespace zeek { namespace BifFunc { extern zeek::ValPtr parse_ftp_pasv_bif(zeek::detail::Frame* frame, const zeek::Args*); }  }
namespace zeek { namespace BifFunc { extern zeek::ValPtr parse_ftp_epsv_bif(zeek::detail::Frame* frame, const zeek::Args*); }  }
namespace zeek { namespace BifFunc { extern zeek::ValPtr fmt_ftp_port_bif(zeek::detail::Frame* frame, const zeek::Args*); }  }

#endif
