# This file was automatically generated by bifcl from communityid.bif.

export {


## Compute the Community ID hash (v1) from a connection identifier.
##
## cid: The identifier of the connection for which to compute the community-id.
##
## Returns: The Community ID hash of the connection identifier as string.
##
global community_id_v1: function(cid: conn_id , seed: count &default=0, do_base64: bool &default=T): string ;

} # end of export section
module GLOBAL;
