# This file was automatically generated by bifcl from const.bif.

export {
##! Declaration of various scripting-layer constants that the Zeek core uses
##! internally.  Documentation and default values for the scripting-layer
##! variables themselves are found in :doc:`/scripts/base/init-bare.zeek`.































} # end of export section
module GLOBAL;
