# This file was automatically generated by bifcl from CPP-load.bif.

export {
##! Definitions of built-in functions related to loading compiled-to-C++
##! scripts.




## Activates the compile-to-C++ scripts associated with the given hash.
##
## h: Hash of the set of C++ scripts.
##
## Returns: True if it was present and loaded, false if not.
##
global load_CPP: function(h: count ): bool ;

} # end of export section
module GLOBAL;
