# This file was automatically generated by bifcl from /usr/src/packages/BUILD/src/spicy/spicy.bif (alternative mode).

export {


module Spicy;






















global max_file_depth_exceeded: event(f: fa_file , args: Files::AnalyzerArgs , limit: count );


global Spicy::__toggle_analyzer: function(tag: any , enable: bool ) : bool ;




global Spicy::__resource_usage: function() : Spicy::ResourceUsage ;

} # end of export section
module GLOBAL;
