# This file was automatically generated by bifcl from telemetry_types.bif.

export {
module Telemetry;


## An enum that specifies which type of metric you're operating on.
type MetricType: enum  {
    COUNTER,	##< Counters track entities that increment over time.
    GAUGE,	##< Gauges track entities that fluctuate over time.
    HISTOGRAM,	##< Histograms group observations into predefined bins.
} ;

} # end of export section
module GLOBAL;
