// This file was automatically generated by bifcl from /usr/src/packages/BUILD/src/packet_analysis/protocol/gtpv1/events.bif (plugin mode).

#if defined(ZEEK_IN_NETVAR) || ! defined(_usr_src_packages_BUILD_build_src_packet_analysis_protocol_gtpv1_events_bif)
#ifndef ZEEK_IN_NETVAR
#ifndef _usr_src_packages_BUILD_build_src_packet_analysis_protocol_gtpv1_events_bif
#define _usr_src_packages_BUILD_build_src_packet_analysis_protocol_gtpv1_events_bif
#include "zeek/zeek-bif.h"
#endif
#endif

extern zeek::EventHandlerPtr new_gtpv1_state; 
namespace zeek { namespace BifEvent {  void enqueue_new_gtpv1_state(zeek::analyzer::Analyzer* analyzer, zeek::Connection* c);  }  }
extern zeek::EventHandlerPtr gtpv1_message; 
namespace zeek { namespace BifEvent {  void enqueue_gtpv1_message(zeek::analyzer::Analyzer* analyzer, zeek::Connection* c, zeek::IntrusivePtr<zeek::Val> hdr);  }  }
extern zeek::EventHandlerPtr gtpv1_g_pdu_packet; 
namespace zeek { namespace BifEvent {  void enqueue_gtpv1_g_pdu_packet(zeek::analyzer::Analyzer* analyzer, zeek::Connection* outer, zeek::IntrusivePtr<zeek::Val> inner_gtp, zeek::IntrusivePtr<zeek::Val> inner_ip);  }  }
extern zeek::EventHandlerPtr gtpv1_create_pdp_ctx_request; 
namespace zeek { namespace BifEvent {  void enqueue_gtpv1_create_pdp_ctx_request(zeek::analyzer::Analyzer* analyzer, zeek::Connection* c, zeek::IntrusivePtr<zeek::Val> hdr, zeek::IntrusivePtr<zeek::Val> elements);  }  }
extern zeek::EventHandlerPtr gtpv1_create_pdp_ctx_response; 
namespace zeek { namespace BifEvent {  void enqueue_gtpv1_create_pdp_ctx_response(zeek::analyzer::Analyzer* analyzer, zeek::Connection* c, zeek::IntrusivePtr<zeek::Val> hdr, zeek::IntrusivePtr<zeek::Val> elements);  }  }
extern zeek::EventHandlerPtr gtpv1_update_pdp_ctx_request; 
namespace zeek { namespace BifEvent {  void enqueue_gtpv1_update_pdp_ctx_request(zeek::analyzer::Analyzer* analyzer, zeek::Connection* c, zeek::IntrusivePtr<zeek::Val> hdr, zeek::IntrusivePtr<zeek::Val> elements);  }  }
extern zeek::EventHandlerPtr gtpv1_update_pdp_ctx_response; 
namespace zeek { namespace BifEvent {  void enqueue_gtpv1_update_pdp_ctx_response(zeek::analyzer::Analyzer* analyzer, zeek::Connection* c, zeek::IntrusivePtr<zeek::Val> hdr, zeek::IntrusivePtr<zeek::Val> elements);  }  }
extern zeek::EventHandlerPtr gtpv1_delete_pdp_ctx_request; 
namespace zeek { namespace BifEvent {  void enqueue_gtpv1_delete_pdp_ctx_request(zeek::analyzer::Analyzer* analyzer, zeek::Connection* c, zeek::IntrusivePtr<zeek::Val> hdr, zeek::IntrusivePtr<zeek::Val> elements);  }  }
extern zeek::EventHandlerPtr gtpv1_delete_pdp_ctx_response; 
namespace zeek { namespace BifEvent {  void enqueue_gtpv1_delete_pdp_ctx_response(zeek::analyzer::Analyzer* analyzer, zeek::Connection* c, zeek::IntrusivePtr<zeek::Val> hdr, zeek::IntrusivePtr<zeek::Val> elements);  }  }

#endif
