// This file was automatically generated by bifcl from /usr/src/packages/BUILD/src/packet_analysis/protocol/gtpv1/functions.bif (plugin mode).

#if defined(ZEEK_IN_NETVAR) || ! defined(_usr_src_packages_BUILD_build_src_packet_analysis_protocol_gtpv1_functions_bif)
#ifndef ZEEK_IN_NETVAR
#ifndef _usr_src_packages_BUILD_build_src_packet_analysis_protocol_gtpv1_functions_bif
#define _usr_src_packages_BUILD_build_src_packet_analysis_protocol_gtpv1_functions_bif
#include "zeek/zeek-bif.h"
#endif
#endif

namespace zeek { namespace BifFunc { namespace PacketAnalyzer::GTPV1 { extern zeek::ValPtr remove_gtpv1_connection_bif(zeek::detail::Frame* frame, const zeek::Args*); }  } }

#endif
