# This file was automatically generated by bifcl from /usr/src/packages/BUILD/src/logging/writers/none/none.bif (plugin mode).

export {



module LogNone;



} # end of export section
module GLOBAL;
