# This file was automatically generated by bifcl from /usr/src/packages/BUILD/src/file_analysis/analyzer/extract/functions.bif (plugin mode).

export {
##! Internal functions used by the extraction file analyzer.

module FileExtract;




## :zeek:see:`FileExtract::set_limit`.
global FileExtract::__set_limit: function(file_id: string , args: any , n: count ): bool ;


module GLOBAL;

} # end of export section
module GLOBAL;
