# This file was automatically generated by bifcl from /usr/src/packages/BUILD/src/packet_analysis/protocol/teredo/functions.bif (plugin mode).

export {
module PacketAnalyzer::TEREDO;




global remove_teredo_connection: function(cid: conn_id ) : bool ;

} # end of export section
module GLOBAL;
