# This file was automatically generated by bifcl from /usr/src/packages/BUILD/src/input/readers/config/config.bif (plugin mode).

export {

module InputConfig;





} # end of export section
module GLOBAL;
