# This file was automatically generated by bifcl from /usr/src/packages/BUILD/src/analyzer/protocol/websocket/types.bif (plugin mode).

export {
module WebSocket;




} # end of export section
module GLOBAL;
