# This file was automatically generated by bifcl from /usr/src/packages/BUILD/src/analyzer/protocol/xmpp/events.bif (plugin mode).

export {
## Generated when a XMPP connection goes encrypted after a successful
## StartTLS exchange between the client and the server.
##
## c: The connection.
global xmpp_starttls: event(c: connection );

} # end of export section
module GLOBAL;
