# This file was automatically generated by bifcl from /usr/src/packages/BUILD/src/file_analysis/analyzer/entropy/events.bif (plugin mode).

export {
## This event is generated each time file analysis performs
## entropy testing on a file.
##
## f: The file.
##
## ent: The results of the entropy testing.
##
global file_entropy: event(f: fa_file , ent: entropy_test_result );
} # end of export section
module GLOBAL;
