# This file was automatically generated by bifcl from /usr/src/packages/BUILD/src/analyzer/protocol/rdp/types.bif (plugin mode).

export {

module RDP;










} # end of export section
module GLOBAL;
