# This file was automatically generated by bifcl from /usr/src/packages/BUILD/src/analyzer/protocol/dhcp/types.bif (plugin mode).

export {
module DHCP;









} # end of export section
module GLOBAL;
