# This file was automatically generated by bifcl from /usr/src/packages/BUILD/src/analyzer/protocol/snmp/types.bif (plugin mode).

export {
module SNMP;
















module GLOBAL;

} # end of export section
module GLOBAL;
