# This file was automatically generated by bifcl from /usr/src/packages/BUILD/src/analyzer/protocol/ssl/types.bif (plugin mode).

export {
module SSL;





module GLOBAL;

} # end of export section
module GLOBAL;
