# This file was automatically generated by bifcl from /usr/src/packages/BUILD/src/input/readers/ascii/ascii.bif (plugin mode).

export {

module InputAscii;









} # end of export section
module GLOBAL;
