# This file was automatically generated by bifcl from /usr/src/packages/BUILD/src/analyzer/protocol/smtp/functions.bif (plugin mode).

export {



## Skips SMTP data until the next email in a connection.
##
## c: The SMTP connection.
##
## .. zeek:see:: skip_http_entity_data
global skip_smtp_data: function(c: connection ): any ;

} # end of export section
module GLOBAL;
