# This file was automatically generated by bifcl from /usr/src/packages/BUILD/src/logging/writers/ascii/ascii.bif (plugin mode).

export {



module LogAscii;
















} # end of export section
module GLOBAL;
