# This file was automatically generated by bifcl from /usr/src/packages/BUILD/src/packet_analysis/protocol/gtpv1/functions.bif (plugin mode).

export {
module PacketAnalyzer::GTPV1;




global remove_gtpv1_connection: function(cid: conn_id ) : bool ;

} # end of export section
module GLOBAL;
