# This file was automatically generated by bifcl from /usr/src/packages/BUILD/src/input/readers/sqlite/sqlite.bif (plugin mode).

export {

module InputSQLite;





} # end of export section
module GLOBAL;
