# This file was automatically generated by bifcl from /usr/src/packages/BUILD/src/analyzer/protocol/ntlm/types.bif (plugin mode).

export {

module NTLM;







} # end of export section
module GLOBAL;
