# This file was automatically generated by bifcl from /usr/src/packages/BUILD/src/input/readers/binary/binary.bif (plugin mode).

export {

module InputBinary;




} # end of export section
module GLOBAL;
