// This file was automatically generated by bifcl from /usr/src/packages/BUILD/src/analyzer/protocol/file/events.bif (plugin mode).

#if defined(ZEEK_IN_NETVAR) || ! defined(_usr_src_packages_BUILD_build_src_analyzer_protocol_file_events_bif)
#ifndef ZEEK_IN_NETVAR
#ifndef _usr_src_packages_BUILD_build_src_analyzer_protocol_file_events_bif
#define _usr_src_packages_BUILD_build_src_analyzer_protocol_file_events_bif
#include "zeek/zeek-bif.h"
#endif
#endif

extern zeek::EventHandlerPtr file_transferred; 
namespace zeek { namespace BifEvent {  void enqueue_file_transferred(zeek::analyzer::Analyzer* analyzer, zeek::Connection* c, zeek::IntrusivePtr<zeek::StringVal> prefix, zeek::IntrusivePtr<zeek::StringVal> descr, zeek::IntrusivePtr<zeek::StringVal> mime_type);  }  }

#endif
