// This file was automatically generated by bifcl from /usr/src/packages/BUILD/src/analyzer/protocol/ntlm/events.bif (plugin mode).

#if defined(ZEEK_IN_NETVAR) || ! defined(_usr_src_packages_BUILD_build_src_analyzer_protocol_ntlm_events_bif)
#ifndef ZEEK_IN_NETVAR
#ifndef _usr_src_packages_BUILD_build_src_analyzer_protocol_ntlm_events_bif
#define _usr_src_packages_BUILD_build_src_analyzer_protocol_ntlm_events_bif
#include "zeek/zeek-bif.h"
#endif
#endif

extern zeek::EventHandlerPtr ntlm_negotiate; 
namespace zeek { namespace BifEvent {  void enqueue_ntlm_negotiate(zeek::analyzer::Analyzer* analyzer, zeek::Connection* c, zeek::IntrusivePtr<zeek::Val> negotiate);  }  }
extern zeek::EventHandlerPtr ntlm_challenge; 
namespace zeek { namespace BifEvent {  void enqueue_ntlm_challenge(zeek::analyzer::Analyzer* analyzer, zeek::Connection* c, zeek::IntrusivePtr<zeek::Val> challenge);  }  }
extern zeek::EventHandlerPtr ntlm_authenticate; 
namespace zeek { namespace BifEvent {  void enqueue_ntlm_authenticate(zeek::analyzer::Analyzer* analyzer, zeek::Connection* c, zeek::IntrusivePtr<zeek::Val> request);  }  }

#endif
