// This file was automatically generated by bifcl from /usr/src/packages/BUILD/src/analyzer/protocol/ntlm/types.bif (plugin mode).

#if defined(ZEEK_IN_NETVAR) || ! defined(_usr_src_packages_BUILD_build_src_analyzer_protocol_ntlm_types_bif)
#ifndef ZEEK_IN_NETVAR
#ifndef _usr_src_packages_BUILD_build_src_analyzer_protocol_ntlm_types_bif
#define _usr_src_packages_BUILD_build_src_analyzer_protocol_ntlm_types_bif
#include "zeek/zeek-bif.h"
#endif
#endif

namespace zeek { namespace BifType { namespace Record{ namespace NTLM {  extern zeek::IntrusivePtr<zeek::RecordType> Negotiate;  } } }}
namespace zeek { namespace BifType { namespace Record{ namespace NTLM {  extern zeek::IntrusivePtr<zeek::RecordType> Challenge;  } } }}
namespace zeek { namespace BifType { namespace Record{ namespace NTLM {  extern zeek::IntrusivePtr<zeek::RecordType> Authenticate;  } } }}
namespace zeek { namespace BifType { namespace Record{ namespace NTLM {  extern zeek::IntrusivePtr<zeek::RecordType> NegotiateFlags;  } } }}
namespace zeek { namespace BifType { namespace Record{ namespace NTLM {  extern zeek::IntrusivePtr<zeek::RecordType> Version;  } } }}
namespace zeek { namespace BifType { namespace Record{ namespace NTLM {  extern zeek::IntrusivePtr<zeek::RecordType> AVs;  } } }}

#endif
