// This file was automatically generated by bifcl from /usr/src/packages/BUILD/src/file_analysis/analyzer/extract/events.bif (plugin mode).

#if defined(ZEEK_IN_NETVAR) || ! defined(_usr_src_packages_BUILD_build_src_file_analysis_analyzer_extract_events_bif)
#ifndef ZEEK_IN_NETVAR
#ifndef _usr_src_packages_BUILD_build_src_file_analysis_analyzer_extract_events_bif
#define _usr_src_packages_BUILD_build_src_file_analysis_analyzer_extract_events_bif
#include "zeek/zeek-bif.h"
#endif
#endif

extern zeek::EventHandlerPtr file_extraction_limit; 
namespace zeek { namespace BifEvent {  void enqueue_file_extraction_limit(zeek::analyzer::Analyzer* analyzer, zeek::IntrusivePtr<zeek::Val> f, zeek::IntrusivePtr<zeek::Val> args, zeek_uint_t limit, zeek_uint_t len);  }  }

#endif
