// This file was automatically generated by bifcl from /usr/src/packages/BUILD/src/analyzer/protocol/imap/events.bif (plugin mode).

#if defined(ZEEK_IN_NETVAR) || ! defined(_usr_src_packages_BUILD_build_src_analyzer_protocol_imap_events_bif)
#ifndef ZEEK_IN_NETVAR
#ifndef _usr_src_packages_BUILD_build_src_analyzer_protocol_imap_events_bif
#define _usr_src_packages_BUILD_build_src_analyzer_protocol_imap_events_bif
#include "zeek/zeek-bif.h"
#endif
#endif

extern zeek::EventHandlerPtr imap_capabilities; 
namespace zeek { namespace BifEvent {  void enqueue_imap_capabilities(zeek::analyzer::Analyzer* analyzer, zeek::Connection* c, zeek::IntrusivePtr<zeek::Val> capabilities);  }  }
extern zeek::EventHandlerPtr imap_starttls; 
namespace zeek { namespace BifEvent {  void enqueue_imap_starttls(zeek::analyzer::Analyzer* analyzer, zeek::Connection* c);  }  }

#endif
