// This file was automatically generated by bifcl from /usr/src/packages/BUILD/src/logging/writers/none/none.bif (plugin mode).

#if defined(ZEEK_IN_NETVAR) || ! defined(_usr_src_packages_BUILD_build_src_logging_writers_none_none_bif)
#ifndef ZEEK_IN_NETVAR
#ifndef _usr_src_packages_BUILD_build_src_logging_writers_none_none_bif
#define _usr_src_packages_BUILD_build_src_logging_writers_none_none_bif
#include "zeek/zeek-bif.h"
#endif
#endif

namespace zeek { namespace BifConst { namespace LogNone {  extern int debug;  }  } }

#endif
