// This file was automatically generated by bifcl from /usr/src/packages/BUILD/src/input/readers/sqlite/sqlite.bif (plugin mode).

#if defined(ZEEK_IN_NETVAR) || ! defined(_usr_src_packages_BUILD_build_src_input_readers_sqlite_sqlite_bif)
#ifndef ZEEK_IN_NETVAR
#ifndef _usr_src_packages_BUILD_build_src_input_readers_sqlite_sqlite_bif
#define _usr_src_packages_BUILD_build_src_input_readers_sqlite_sqlite_bif
#include "zeek/zeek-bif.h"
#endif
#endif

namespace zeek { namespace BifConst { namespace InputSQLite {  extern zeek::IntrusivePtr<zeek::StringVal> set_separator;  }  } }
namespace zeek { namespace BifConst { namespace InputSQLite {  extern zeek::IntrusivePtr<zeek::StringVal> unset_field;  }  } }
namespace zeek { namespace BifConst { namespace InputSQLite {  extern zeek::IntrusivePtr<zeek::StringVal> empty_field;  }  } }

#endif
