// This file was automatically generated by bifcl from /usr/src/packages/BUILD/src/analyzer/protocol/dhcp/types.bif (plugin mode).

#if defined(ZEEK_IN_NETVAR) || ! defined(_usr_src_packages_BUILD_build_src_analyzer_protocol_dhcp_types_bif)
#ifndef ZEEK_IN_NETVAR
#ifndef _usr_src_packages_BUILD_build_src_analyzer_protocol_dhcp_types_bif
#define _usr_src_packages_BUILD_build_src_analyzer_protocol_dhcp_types_bif
#include "zeek/zeek-bif.h"
#endif
#endif

namespace zeek { namespace BifType { namespace Record{ namespace DHCP {  extern zeek::IntrusivePtr<zeek::RecordType> Msg;  } } }}
namespace zeek { namespace BifType { namespace Vector{ namespace DHCP {  extern zeek::IntrusivePtr<zeek::VectorType> Addrs;  } } }}
namespace zeek { namespace BifType { namespace Record{ namespace DHCP {  extern zeek::IntrusivePtr<zeek::RecordType> SubOpt;  } } }}
namespace zeek { namespace BifType { namespace Vector{ namespace DHCP {  extern zeek::IntrusivePtr<zeek::VectorType> SubOpts;  } } }}
namespace zeek { namespace BifType { namespace Record{ namespace DHCP {  extern zeek::IntrusivePtr<zeek::RecordType> ClientFQDN;  } } }}
namespace zeek { namespace BifType { namespace Record{ namespace DHCP {  extern zeek::IntrusivePtr<zeek::RecordType> ClientID;  } } }}
namespace zeek { namespace BifType { namespace Record{ namespace DHCP {  extern zeek::IntrusivePtr<zeek::RecordType> Options;  } } }}

#endif
