// This file was automatically generated by bifcl from /usr/src/packages/BUILD/src/analyzer/protocol/ident/events.bif (plugin mode).

#if defined(ZEEK_IN_NETVAR) || ! defined(_usr_src_packages_BUILD_build_src_analyzer_protocol_ident_events_bif)
#ifndef ZEEK_IN_NETVAR
#ifndef _usr_src_packages_BUILD_build_src_analyzer_protocol_ident_events_bif
#define _usr_src_packages_BUILD_build_src_analyzer_protocol_ident_events_bif
#include "zeek/zeek-bif.h"
#endif
#endif

extern zeek::EventHandlerPtr ident_request; 
namespace zeek { namespace BifEvent {  void enqueue_ident_request(zeek::analyzer::Analyzer* analyzer, zeek::Connection* c, zeek::IntrusivePtr<zeek::PortVal> lport, zeek::IntrusivePtr<zeek::PortVal> rport);  }  }
extern zeek::EventHandlerPtr ident_reply; 
namespace zeek { namespace BifEvent {  void enqueue_ident_reply(zeek::analyzer::Analyzer* analyzer, zeek::Connection* c, zeek::IntrusivePtr<zeek::PortVal> lport, zeek::IntrusivePtr<zeek::PortVal> rport, zeek::IntrusivePtr<zeek::StringVal> user_id, zeek::IntrusivePtr<zeek::StringVal> system);  }  }
extern zeek::EventHandlerPtr ident_error; 
namespace zeek { namespace BifEvent {  void enqueue_ident_error(zeek::analyzer::Analyzer* analyzer, zeek::Connection* c, zeek::IntrusivePtr<zeek::PortVal> lport, zeek::IntrusivePtr<zeek::PortVal> rport, zeek::IntrusivePtr<zeek::StringVal> line);  }  }

#endif
