// This file was automatically generated by bifcl from /usr/src/packages/BUILD/src/analyzer/protocol/ntp/events.bif (plugin mode).

#if defined(ZEEK_IN_NETVAR) || ! defined(_usr_src_packages_BUILD_build_src_analyzer_protocol_ntp_events_bif)
#ifndef ZEEK_IN_NETVAR
#ifndef _usr_src_packages_BUILD_build_src_analyzer_protocol_ntp_events_bif
#define _usr_src_packages_BUILD_build_src_analyzer_protocol_ntp_events_bif
#include "zeek/zeek-bif.h"
#endif
#endif

extern zeek::EventHandlerPtr ntp_message; 
namespace zeek { namespace BifEvent {  void enqueue_ntp_message(zeek::analyzer::Analyzer* analyzer, zeek::Connection* c, int is_orig, zeek::IntrusivePtr<zeek::Val> msg);  }  }

#endif
