// This file was automatically generated by bifcl from /usr/src/packages/BUILD/src/analyzer/protocol/ntp/types.bif (plugin mode).

#if defined(ZEEK_IN_NETVAR) || ! defined(_usr_src_packages_BUILD_build_src_analyzer_protocol_ntp_types_bif)
#ifndef ZEEK_IN_NETVAR
#ifndef _usr_src_packages_BUILD_build_src_analyzer_protocol_ntp_types_bif
#define _usr_src_packages_BUILD_build_src_analyzer_protocol_ntp_types_bif
#include "zeek/zeek-bif.h"
#endif
#endif

namespace zeek { namespace BifType { namespace Record{ namespace NTP {  extern zeek::IntrusivePtr<zeek::RecordType> StandardMessage;  } } }}
namespace zeek { namespace BifType { namespace Record{ namespace NTP {  extern zeek::IntrusivePtr<zeek::RecordType> ControlMessage;  } } }}
namespace zeek { namespace BifType { namespace Record{ namespace NTP {  extern zeek::IntrusivePtr<zeek::RecordType> Mode7Message;  } } }}
namespace zeek { namespace BifType { namespace Record{ namespace NTP {  extern zeek::IntrusivePtr<zeek::RecordType> Message;  } } }}

#endif
