// This file was automatically generated by bifcl from /usr/src/packages/BUILD/src/packet_analysis/protocol/vxlan/events.bif (plugin mode).

#if defined(ZEEK_IN_NETVAR) || ! defined(_usr_src_packages_BUILD_build_src_packet_analysis_protocol_vxlan_events_bif)
#ifndef ZEEK_IN_NETVAR
#ifndef _usr_src_packages_BUILD_build_src_packet_analysis_protocol_vxlan_events_bif
#define _usr_src_packages_BUILD_build_src_packet_analysis_protocol_vxlan_events_bif
#include "zeek/zeek-bif.h"
#endif
#endif

extern zeek::EventHandlerPtr vxlan_packet; 
namespace zeek { namespace BifEvent {  void enqueue_vxlan_packet(zeek::analyzer::Analyzer* analyzer, zeek::Connection* outer, zeek::IntrusivePtr<zeek::Val> inner, zeek_uint_t vni);  }  }

#endif
