// This file was automatically generated by bifcl from /usr/src/packages/BUILD/src/logging/writers/sqlite/sqlite.bif (plugin mode).

#if defined(ZEEK_IN_NETVAR) || ! defined(_usr_src_packages_BUILD_build_src_logging_writers_sqlite_sqlite_bif)
#ifndef ZEEK_IN_NETVAR
#ifndef _usr_src_packages_BUILD_build_src_logging_writers_sqlite_sqlite_bif
#define _usr_src_packages_BUILD_build_src_logging_writers_sqlite_sqlite_bif
#include "zeek/zeek-bif.h"
#endif
#endif

namespace zeek { namespace BifConst { namespace LogSQLite {  extern zeek::IntrusivePtr<zeek::StringVal> set_separator;  }  } }
namespace zeek { namespace BifConst { namespace LogSQLite {  extern zeek::IntrusivePtr<zeek::StringVal> empty_field;  }  } }
namespace zeek { namespace BifConst { namespace LogSQLite {  extern zeek::IntrusivePtr<zeek::StringVal> unset_field;  }  } }
namespace BifEnum { namespace LogSQLite { enum SQLiteSynchronous {
	SQLITE_SYNCHRONOUS_DEFAULT,
	SQLITE_SYNCHRONOUS_OFF,
	SQLITE_SYNCHRONOUS_NORMAL,
	SQLITE_SYNCHRONOUS_FULL,
	SQLITE_SYNCHRONOUS_EXTRA,
}; } }
namespace zeek { namespace BifType { namespace Enum{ namespace LogSQLite {  extern zeek::IntrusivePtr<zeek::EnumType> SQLiteSynchronous;  } } }}
namespace BifEnum { namespace LogSQLite { enum SQLiteJournalMode {
	SQLITE_JOURNAL_MODE_DEFAULT,
	SQLITE_JOURNAL_MODE_DELETE,
	SQLITE_JOURNAL_MODE_TRUNCATE,
	SQLITE_JOURNAL_MODE_PERSIST,
	SQLITE_JOURNAL_MODE_MEMORY,
	SQLITE_JOURNAL_MODE_WAL,
	SQLITE_JOURNAL_MODE_OFF,
}; } }
namespace zeek { namespace BifType { namespace Enum{ namespace LogSQLite {  extern zeek::IntrusivePtr<zeek::EnumType> SQLiteJournalMode;  } } }}
namespace zeek { namespace BifConst { namespace LogSQLite {  extern zeek::IntrusivePtr<zeek::Val> synchronous;  }  } }
namespace zeek { namespace BifConst { namespace LogSQLite {  extern zeek::IntrusivePtr<zeek::Val> journal_mode;  }  } }

#endif
