// This file was automatically generated by bifcl from /usr/src/packages/BUILD/src/input/readers/raw/raw.bif (plugin mode).

#if defined(ZEEK_IN_NETVAR) || ! defined(_usr_src_packages_BUILD_build_src_input_readers_raw_raw_bif)
#ifndef ZEEK_IN_NETVAR
#ifndef _usr_src_packages_BUILD_build_src_input_readers_raw_raw_bif
#define _usr_src_packages_BUILD_build_src_input_readers_raw_raw_bif
#include "zeek/zeek-bif.h"
#endif
#endif

namespace zeek { namespace BifConst { namespace InputRaw {  extern zeek::IntrusivePtr<zeek::StringVal> record_separator;  }  } }

#endif
