// This file was automatically generated by bifcl from /usr/src/packages/BUILD/src/analyzer/protocol/stream_event/events.bif (plugin mode).

#if defined(ZEEK_IN_NETVAR) || ! defined(_usr_src_packages_BUILD_build_src_analyzer_protocol_stream_event_events_bif)
#ifndef ZEEK_IN_NETVAR
#ifndef _usr_src_packages_BUILD_build_src_analyzer_protocol_stream_event_events_bif
#define _usr_src_packages_BUILD_build_src_analyzer_protocol_stream_event_events_bif
#include "zeek/zeek-bif.h"
#endif
#endif

extern zeek::EventHandlerPtr stream_deliver; 
namespace zeek { namespace BifEvent {  void enqueue_stream_deliver(zeek::analyzer::Analyzer* analyzer, zeek::Connection* c, int is_orig, zeek::IntrusivePtr<zeek::StringVal> data);  }  }
extern zeek::EventHandlerPtr stream_undelivered; 
namespace zeek { namespace BifEvent {  void enqueue_stream_undelivered(zeek::analyzer::Analyzer* analyzer, zeek::Connection* c, int is_orig, zeek_uint_t seq, zeek_uint_t len);  }  }

#endif
