// This file was automatically generated by bifcl from /usr/src/packages/BUILD/src/input/readers/config/config.bif (plugin mode).

#if defined(ZEEK_IN_NETVAR) || ! defined(_usr_src_packages_BUILD_build_src_input_readers_config_config_bif)
#ifndef ZEEK_IN_NETVAR
#ifndef _usr_src_packages_BUILD_build_src_input_readers_config_config_bif
#define _usr_src_packages_BUILD_build_src_input_readers_config_config_bif
#include "zeek/zeek-bif.h"
#endif
#endif

namespace zeek { namespace BifConst { namespace InputConfig {  extern zeek::IntrusivePtr<zeek::StringVal> set_separator;  }  } }
namespace zeek { namespace BifConst { namespace InputConfig {  extern zeek::IntrusivePtr<zeek::StringVal> empty_field;  }  } }
namespace zeek { namespace BifConst { namespace InputConfig {  extern int fail_on_file_problem;  }  } }

#endif
